spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: HTML
  devtools:
    restart:
      trigger-file: .trigger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/whoSchema?serverTimezone=Asia/Taipei&useUnicode=true&characterEncoding=utf-8
    username: wumy
    password: pass1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null




